# MySQL配置统一
# 数据库名：smart_community
# 数据库密码：123
# 数据库版本:MySQL5.7.*

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart_community?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
#新加quartz配置
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      max-active: 100
#      initial-size: 3
#      min-idle: 3
#      max-wait: 10000
#  quartz:
#    job-store-type: jdbc
#    overwrite-existing-jobs: true
#    properties:
#      org:
#        quartz:
#          scheduler:
#            instanceName: MyScheduler
#            instanceId: AUTO
#          jobStore:
#            class: org.quartz.impl.jdbcjobstore.JobStoreTX
#            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
#            tablePrefix: QRTZ_
#            useProperties: false
#          threadPool:
#            class: org.quartz.simpl.SimpleThreadPool
#            threadCount: 10
#            threadPriority: 5
#            threadsInheritContextClassLoaderOfInitializingThread: true
#新加quartz配置
  mvc:
    servlet:
      load-on-startup: 1



# Mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.woniuxy.smart_community.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

# 日志文件打印级别
logging:
  level:
    com.woniuxy.smart_community.dao: debug



#PageHelper分页插件配置
#pagehelper:
#  #dialect: mysql
#  dialect: com.github.pagehelper.dialect.helper.MySqlDialect
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql
