spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rbac_shiro?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
#    ???
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.woniuxy.springbootshiro.dao: debug


